// Edit this file to add prints, change prices, or take something off sale.
// Prices are in cents (USD). Set your own margin on top of what Richard charges you per size.
//
// Regenerated by scripts/generate-catalog.mjs — titles and descriptions
// were auto-filled from filenames, edit them here to your liking.

export type SizeKey = "4x6" | "8x12" | "12x18" | "16x24" | "20x30";

export const SIZES: { key: SizeKey; label: string; priceCents: number }[] = [
  { key: "4x6", label: '4 × 6"', priceCents: 1500 },
  { key: "8x12", label: '8 × 12"', priceCents: 3500 },
  { key: "12x18", label: '12 × 18"', priceCents: 6500 },
  { key: "16x24", label: '16 × 24"', priceCents: 11000 },
  { key: "20x30", label: '20 × 30"', priceCents: 16500 },
];

export type Product = {
  slug: string;
  title: string;
  description: string;
  imageFile: string;
};

export const PRODUCTS: Product[] = [
  {
    slug: "000015000008",
    title: "000015000008",
    description: "",
    imageFile: "000015000008.jpg",
  },
  {
    slug: "000015000028-copy",
    title: "000015000028 Copy",
    description: "",
    imageFile: "000015000028-copy.jpg",
  },
  {
    slug: "000015000035",
    title: "000015000035",
    description: "",
    imageFile: "000015000035.jpg",
  },
  {
    slug: "000034960004",
    title: "000034960004",
    description: "",
    imageFile: "000034960004.jpg",
  },
  {
    slug: "000034980019",
    title: "000034980019",
    description: "",
    imageFile: "000034980019.jpg",
  },
  {
    slug: "000034990001",
    title: "000034990001",
    description: "",
    imageFile: "000034990001.jpg",
  },
  {
    slug: "000067340020",
    title: "000067340020",
    description: "",
    imageFile: "000067340020.jpg",
  },
  {
    slug: "000067530013",
    title: "000067530013",
    description: "",
    imageFile: "000067530013.jpg",
  },
  {
    slug: "000074490001",
    title: "000074490001",
    description: "",
    imageFile: "000074490001.jpg",
  },
  {
    slug: "000074490037",
    title: "000074490037",
    description: "",
    imageFile: "000074490037.jpg",
  },
  {
    slug: "000102270028",
    title: "000102270028",
    description: "",
    imageFile: "000102270028.jpg",
  },
  {
    slug: "000102280023",
    title: "000102280023",
    description: "",
    imageFile: "000102280023.jpg",
  },
  {
    slug: "000102280024",
    title: "000102280024",
    description: "",
    imageFile: "000102280024.jpg",
  },
  {
    slug: "000102300005",
    title: "000102300005",
    description: "",
    imageFile: "000102300005.jpg",
  },
  {
    slug: "003",
    title: "003",
    description: "",
    imageFile: "003.jpg",
  },
  {
    slug: "269e2c3b-10ef-4331-935e-39bc7d566ea5-1-201-a",
    title: "269E2C3B 10EF 4331 935E 39BC7D566EA5 1 201 A",
    description: "",
    imageFile: "269e2c3b-10ef-4331-935e-39bc7d566ea5-1-201-a.jpg",
  },
  {
    slug: "305410de-99ce-4678-a647-904488d24173-1-201-a",
    title: "305410DE 99CE 4678 A647 904488D24173 1 201 A",
    description: "",
    imageFile: "305410de-99ce-4678-a647-904488d24173-1-201-a.jpg",
  },
  {
    slug: "6c588868-7ae4-44db-be51-10016e8712f5-1-102-o",
    title: "6C588868 7AE4 44DB BE51 10016E8712F5 1 102 O",
    description: "",
    imageFile: "6c588868-7ae4-44db-be51-10016e8712f5-1-102-o.jpg",
  },
  {
    slug: "979be5a4-a8d2-4da4-9dfc-4b574af518c2",
    title: "979BE5A4 A8D2 4DA4 9DFC 4B574AF518C2",
    description: "",
    imageFile: "979be5a4-a8d2-4da4-9dfc-4b574af518c2.jpg",
  },
  {
    slug: "9ec04fb3-b461-4a7d-a7c1-d7c5c20e72b4",
    title: "9EC04FB3 B461 4A7D A7C1 D7C5C20E72B4",
    description: "",
    imageFile: "9ec04fb3-b461-4a7d-a7c1-d7c5c20e72b4.jpg",
  },
  {
    slug: "a5b2884b-4ff5-41d3-9c69-c762ecb0786f",
    title: "A5B2884B 4FF5 41D3 9C69 C762ECB0786F",
    description: "",
    imageFile: "a5b2884b-4ff5-41d3-9c69-c762ecb0786f.jpg",
  },
  {
    slug: "img-2977",
    title: "IMG 2977",
    description: "",
    imageFile: "img-2977.jpg",
  },
  {
    slug: "img-2978",
    title: "IMG 2978",
    description: "",
    imageFile: "img-2978.jpg",
  },
  {
    slug: "img-2979",
    title: "IMG 2979",
    description: "",
    imageFile: "img-2979.jpg",
  },
  {
    slug: "img-2993",
    title: "IMG 2993",
    description: "",
    imageFile: "img-2993.jpg",
  },
  {
    slug: "img-3070",
    title: "IMG 3070",
    description: "",
    imageFile: "img-3070.jpg",
  },
  {
    slug: "img-3089",
    title: "IMG 3089",
    description: "",
    imageFile: "img-3089.jpg",
  },
  {
    slug: "img-3496",
    title: "IMG 3496",
    description: "",
    imageFile: "img-3496.jpg",
  },
  {
    slug: "weswai0-weswai0-r1-e039",
    title: "WesWai0 WesWai0 R1 E039",
    description: "",
    imageFile: "weswai0-weswai0-r1-e039.jpg",
  },
  {
    slug: "weslwa1-weslwa1-r1-072-34a",
    title: "WeslWa1 WeslWa1 R1 072 34A",
    description: "",
    imageFile: "weslwa1-weslwa1-r1-072-34a.jpg",
  },
  {
    slug: "wesleywait200032-r1-028-12a",
    title: "Wesleywait200032 R1 028 12A",
    description: "",
    imageFile: "wesleywait200032-r1-028-12a.jpg",
  },
  {
    slug: "wesleywait476096-r1-017-7",
    title: "Wesleywait476096 R1 017 7",
    description: "",
    imageFile: "wesleywait476096-r1-017-7.jpg",
  },
  {
    slug: "wesleywait476096-r1-021-9",
    title: "Wesleywait476096 R1 021 9",
    description: "",
    imageFile: "wesleywait476096-r1-021-9.jpg",
  },
  {
    slug: "wesleywait476096-r1-037-17",
    title: "Wesleywait476096 R1 037 17",
    description: "",
    imageFile: "wesleywait476096-r1-037-17.jpg",
  },
];

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getSize(key: string) {
  return SIZES.find((s) => s.key === key);
}
