// Run: node scripts/generate-catalog.mjs ./path/to/your/curated-folder
//
// What it does:
//   1. Reads every image in the folder you point it at
//   2. Resizes + compresses a web-ready copy into public/images/
//   3. Writes lib/products.ts with one entry per image, auto-slugged
//      and auto-titled from the filename
//
// Naming: name your files however's natural to you, e.g.
//   "Coney Island Boardwalk.jpg" -> slug "coney-island-boardwalk",
//   title "Coney Island Boardwalk". Edit titles/descriptions in
//   lib/products.ts by hand afterward — this just gets you unstuck
//   from typing 34 blocks manually.
//
// Re-running is safe: it overwrites public/images/ and lib/products.ts
// based on whatever's in the source folder at the time.

import sharp from "sharp";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, "..");

const sourceDir = process.argv[2];
if (!sourceDir) {
  console.error("Usage: node scripts/generate-catalog.mjs ./path/to/curated-folder");
  process.exit(1);
}

const outputImagesDir = path.join(projectRoot, "public", "images");
const productsFile = path.join(projectRoot, "lib", "products.ts");

const VALID_EXT = new Set([".jpg", ".jpeg", ".png", ".tif", ".tiff", ".webp"]);
const MAX_DIMENSION = 2000; // long edge, in px — plenty for a browser
const JPEG_QUALITY = 82;

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[_]+/g, "-")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

function titleize(name) {
  return name
    .replace(/[-_]+/g, " ")
    .trim()
    .split(" ")
    .map((w) => (w.length ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");
}

async function main() {
  await fs.mkdir(outputImagesDir, { recursive: true });

  const files = (await fs.readdir(sourceDir)).filter((f) =>
    VALID_EXT.has(path.extname(f).toLowerCase())
  );

  if (files.length === 0) {
    console.error(`No images found in ${sourceDir}`);
    process.exit(1);
  }

  const products = [];

  for (const file of files) {
    const nameNoExt = path.basename(file, path.extname(file));
    const slug = slugify(nameNoExt);
    const title = titleize(nameNoExt);
    const outFile = `${slug}.jpg`;

    const inputPath = path.join(sourceDir, file);
    const outputPath = path.join(outputImagesDir, outFile);

    const before = (await fs.stat(inputPath)).size;

    try {
      await sharp(inputPath, { limitInputPixels: false })
        .rotate() // apply EXIF orientation so nothing comes out sideways
        .resize({ width: MAX_DIMENSION, height: MAX_DIMENSION, fit: "inside", withoutEnlargement: true })
        .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
        .toFile(outputPath);
    } catch (err) {
      console.error(`  SKIPPED ${file}: ${err.message}`);
      continue;
    }

    const after = (await fs.stat(outputPath)).size;
    console.log(
      `${file} -> public/images/${outFile}  (${(before / 1024 / 1024).toFixed(1)}MB -> ${(after / 1024).toFixed(0)}KB)`
    );

    products.push({ slug, title, imageFile: outFile });
  }

  const productsSource = `// Edit this file to add prints, change prices, or take something off sale.
// Prices are in cents (USD). Set your own margin on top of what Richard charges you per size.
//
// Regenerated by scripts/generate-catalog.mjs — titles and descriptions
// were auto-filled from filenames, edit them here to your liking.

export type SizeKey = "4x6" | "8x12" | "12x18" | "16x24" | "20x30";

export const SIZES: { key: SizeKey; label: string; priceCents: number }[] = [
  { key: "4x6", label: '4 × 6"', priceCents: 1500 },
  { key: "8x12", label: '8 × 12"', priceCents: 3500 },
  { key: "12x18", label: '12 × 18"', priceCents: 6500 },
  { key: "16x24", label: '16 × 24"', priceCents: 11000 },
  { key: "20x30", label: '20 × 30"', priceCents: 16500 },
];

export type Product = {
  slug: string;
  title: string;
  description: string;
  imageFile: string;
};

export const PRODUCTS: Product[] = [
${products
  .map(
    (p) => `  {
    slug: "${p.slug}",
    title: "${p.title}",
    description: "",
    imageFile: "${p.imageFile}",
  },`
  )
  .join("\n")}
];

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getSize(key: string) {
  return SIZES.find((s) => s.key === key);
}
`;

  await fs.writeFile(productsFile, productsSource);
  console.log(`\nWrote ${products.length} entries to lib/products.ts`);
  console.log("Descriptions are blank — fill those in by hand when you get a chance.");
}

main();
